'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace LibService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Auteur", [Namespace]:="http://schemas.datacontract.org/2004/07/LIbrairieServer"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Auteur
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateNaissanceField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrenomField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateNaissance() As Date
            Get
                Return Me.DateNaissanceField
            End Get
            Set
                If (Me.DateNaissanceField.Equals(value) <> true) Then
                    Me.DateNaissanceField = value
                    Me.RaisePropertyChanged("DateNaissance")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nom() As String
            Get
                Return Me.NomField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomField, value) <> true) Then
                    Me.NomField = value
                    Me.RaisePropertyChanged("Nom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Prenom() As String
            Get
                Return Me.PrenomField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrenomField, value) <> true) Then
                    Me.PrenomField = value
                    Me.RaisePropertyChanged("Prenom")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="LibService.IService")>  _
    Public Interface IService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetData", ReplyAction:="http://tempuri.org/IService/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetData", ReplyAction:="http://tempuri.org/IService/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As LibService.CompositeType) As LibService.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As LibService.CompositeType) As System.Threading.Tasks.Task(Of LibService.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetNbAuteur", ReplyAction:="http://tempuri.org/IService/GetNbAuteurResponse")>  _
        Function GetNbAuteur() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetNbAuteur", ReplyAction:="http://tempuri.org/IService/GetNbAuteurResponse")>  _
        Function GetNbAuteurAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetAllAuteur", ReplyAction:="http://tempuri.org/IService/GetAllAuteurResponse")>  _
        Function GetAllAuteur() As LibService.Auteur()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetAllAuteur", ReplyAction:="http://tempuri.org/IService/GetAllAuteurResponse")>  _
        Function GetAllAuteurAsync() As System.Threading.Tasks.Task(Of LibService.Auteur())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetNBLivreByAuteur", ReplyAction:="http://tempuri.org/IService/GetNBLivreByAuteurResponse")>  _
        Function GetNBLivreByAuteur(ByVal auteurId As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetNBLivreByAuteur", ReplyAction:="http://tempuri.org/IService/GetNBLivreByAuteurResponse")>  _
        Function GetNBLivreByAuteurAsync(ByVal auteurId As Integer) As System.Threading.Tasks.Task(Of Integer)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceChannel
        Inherits LibService.IService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceClient
        Inherits System.ServiceModel.ClientBase(Of LibService.IService)
        Implements LibService.IService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements LibService.IService.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements LibService.IService.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As LibService.CompositeType) As LibService.CompositeType Implements LibService.IService.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As LibService.CompositeType) As System.Threading.Tasks.Task(Of LibService.CompositeType) Implements LibService.IService.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
        
        Public Function GetNbAuteur() As Integer Implements LibService.IService.GetNbAuteur
            Return MyBase.Channel.GetNbAuteur
        End Function
        
        Public Function GetNbAuteurAsync() As System.Threading.Tasks.Task(Of Integer) Implements LibService.IService.GetNbAuteurAsync
            Return MyBase.Channel.GetNbAuteurAsync
        End Function
        
        Public Function GetAllAuteur() As LibService.Auteur() Implements LibService.IService.GetAllAuteur
            Return MyBase.Channel.GetAllAuteur
        End Function
        
        Public Function GetAllAuteurAsync() As System.Threading.Tasks.Task(Of LibService.Auteur()) Implements LibService.IService.GetAllAuteurAsync
            Return MyBase.Channel.GetAllAuteurAsync
        End Function
        
        Public Function GetNBLivreByAuteur(ByVal auteurId As Integer) As Integer Implements LibService.IService.GetNBLivreByAuteur
            Return MyBase.Channel.GetNBLivreByAuteur(auteurId)
        End Function
        
        Public Function GetNBLivreByAuteurAsync(ByVal auteurId As Integer) As System.Threading.Tasks.Task(Of Integer) Implements LibService.IService.GetNBLivreByAuteurAsync
            Return MyBase.Channel.GetNBLivreByAuteurAsync(auteurId)
        End Function
    End Class
End Namespace
